# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splint_gui.ui'
#
# Created: Thu Oct 22 15:42:17 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 606)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.OutputTextEdit = QtGui.QTextEdit(self.tab)
        self.OutputTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.OutputTextEdit.setObjectName("OutputTextEdit")
        self.gridLayout.addWidget(self.OutputTextEdit, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.FilesLineEdit = QtGui.QLineEdit(self.tab)
        self.FilesLineEdit.setObjectName("FilesLineEdit")
        self.horizontalLayout_3.addWidget(self.FilesLineEdit)
        self.ChoosePushButton = QtGui.QPushButton(self.tab)
        self.ChoosePushButton.setObjectName("ChoosePushButton")
        self.horizontalLayout_3.addWidget(self.ChoosePushButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.CheckPushButton = QtGui.QPushButton(self.tab)
        self.CheckPushButton.setObjectName("CheckPushButton")
        self.gridLayout.addWidget(self.CheckPushButton, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weakModeRadioButton = QtGui.QRadioButton(self.groupBox)
        self.weakModeRadioButton.setObjectName("weakModeRadioButton")
        self.horizontalLayout.addWidget(self.weakModeRadioButton)
        self.standardModeRadioButton = QtGui.QRadioButton(self.groupBox)
        self.standardModeRadioButton.setChecked(True)
        self.standardModeRadioButton.setObjectName("standardModeRadioButton")
        self.horizontalLayout.addWidget(self.standardModeRadioButton)
        self.checksModeRadioButton = QtGui.QRadioButton(self.groupBox)
        self.checksModeRadioButton.setObjectName("checksModeRadioButton")
        self.horizontalLayout.addWidget(self.checksModeRadioButton)
        self.strictModeRadioButton = QtGui.QRadioButton(self.groupBox)
        self.strictModeRadioButton.setObjectName("strictModeRadioButton")
        self.horizontalLayout.addWidget(self.strictModeRadioButton)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.includedirsLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.includedirsLineEdit.setObjectName("includedirsLineEdit")
        self.horizontalLayout_2.addWidget(self.includedirsLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.definesLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.definesLineEdit.setObjectName("definesLineEdit")
        self.horizontalLayout_4.addWidget(self.definesLineEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(858, 51, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.SplintOptionsGroupBox = QtGui.QGroupBox(self.tab_2)
        self.SplintOptionsGroupBox.setObjectName("SplintOptionsGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.SplintOptionsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.compdefCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.compdefCheckBox.setObjectName("compdefCheckBox")
        self.gridLayout_2.addWidget(self.compdefCheckBox, 5, 1, 1, 1)
        self.usedefCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.usedefCheckBox.setObjectName("usedefCheckBox")
        self.gridLayout_2.addWidget(self.usedefCheckBox, 5, 3, 1, 1)
        self.matchanyintegralCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.matchanyintegralCheckBox.setObjectName("matchanyintegralCheckBox")
        self.gridLayout_2.addWidget(self.matchanyintegralCheckBox, 7, 1, 1, 1)
        self.imptypeCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.imptypeCheckBox.setObjectName("imptypeCheckBox")
        self.gridLayout_2.addWidget(self.imptypeCheckBox, 7, 3, 1, 1)
        self.ptrnegateCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.ptrnegateCheckBox.setObjectName("ptrnegateCheckBox")
        self.gridLayout_2.addWidget(self.ptrnegateCheckBox, 11, 1, 1, 1)
        self.bufferoverflowhighCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.bufferoverflowhighCheckBox.setObjectName("bufferoverflowhighCheckBox")
        self.gridLayout_2.addWidget(self.bufferoverflowhighCheckBox, 11, 3, 1, 1)
        self.label = QtGui.QLabel(self.SplintOptionsGroupBox)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.typeCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.typeCheckBox.setObjectName("typeCheckBox")
        self.gridLayout_2.addWidget(self.typeCheckBox, 12, 0, 1, 1)
        self.mayaliasuniqueCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.mayaliasuniqueCheckBox.setObjectName("mayaliasuniqueCheckBox")
        self.gridLayout_2.addWidget(self.mayaliasuniqueCheckBox, 12, 1, 1, 1)
        self.boolopsCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.boolopsCheckBox.setObjectName("boolopsCheckBox")
        self.gridLayout_2.addWidget(self.boolopsCheckBox, 12, 3, 1, 1)
        self.nullpassCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.nullpassCheckBox.setObjectName("nullpassCheckBox")
        self.gridLayout_2.addWidget(self.nullpassCheckBox, 13, 0, 1, 1)
        self.line = QtGui.QFrame(self.SplintOptionsGroupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 8)
        self.nullderefCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.nullderefCheckBox.setObjectName("nullderefCheckBox")
        self.gridLayout_2.addWidget(self.nullderefCheckBox, 13, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.SplintOptionsGroupBox)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 1, 1, 1)
        self.pathtosplintLabel = QtGui.QLabel(self.SplintOptionsGroupBox)
        self.pathtosplintLabel.setObjectName("pathtosplintLabel")
        self.gridLayout_2.addWidget(self.pathtosplintLabel, 0, 2, 1, 1)
        self.pathtosplintLineEdit = QtGui.QLineEdit(self.SplintOptionsGroupBox)
        self.pathtosplintLineEdit.setObjectName("pathtosplintLineEdit")
        self.gridLayout_2.addWidget(self.pathtosplintLineEdit, 0, 3, 1, 1)
        self.pathtosplintPushButton = QtGui.QPushButton(self.SplintOptionsGroupBox)
        self.pathtosplintPushButton.setObjectName("pathtosplintPushButton")
        self.gridLayout_2.addWidget(self.pathtosplintPushButton, 0, 7, 1, 1)
        self.formattypeCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.formattypeCheckBox.setObjectName("formattypeCheckBox")
        self.gridLayout_2.addWidget(self.formattypeCheckBox, 5, 6, 1, 1)
        self.onlytransCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.onlytransCheckBox.setObjectName("onlytransCheckBox")
        self.gridLayout_2.addWidget(self.onlytransCheckBox, 7, 6, 1, 1)
        self.globsCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.globsCheckBox.setObjectName("globsCheckBox")
        self.gridLayout_2.addWidget(self.globsCheckBox, 11, 6, 1, 1)
        self.exportlocalCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.exportlocalCheckBox.setObjectName("exportlocalCheckBox")
        self.gridLayout_2.addWidget(self.exportlocalCheckBox, 13, 6, 1, 1)
        self.posixlibCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.posixlibCheckBox.setObjectName("posixlibCheckBox")
        self.gridLayout_2.addWidget(self.posixlibCheckBox, 7, 0, 1, 1)
        self.unixlibCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.unixlibCheckBox.setObjectName("unixlibCheckBox")
        self.gridLayout_2.addWidget(self.unixlibCheckBox, 5, 0, 1, 1)
        self.warnposixCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.warnposixCheckBox.setObjectName("warnposixCheckBox")
        self.gridLayout_2.addWidget(self.warnposixCheckBox, 11, 0, 1, 1)
        self.posixstrictlibCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.posixstrictlibCheckBox.setObjectName("posixstrictlibCheckBox")
        self.gridLayout_2.addWidget(self.posixstrictlibCheckBox, 10, 0, 1, 1)
        self.preprocCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.preprocCheckBox.setObjectName("preprocCheckBox")
        self.gridLayout_2.addWidget(self.preprocCheckBox, 10, 1, 1, 1)
        self.mustfreefreshCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.mustfreefreshCheckBox.setObjectName("mustfreefreshCheckBox")
        self.gridLayout_2.addWidget(self.mustfreefreshCheckBox, 10, 6, 1, 1)
        self.unrecogCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.unrecogCheckBox.setObjectName("unrecogCheckBox")
        self.gridLayout_2.addWidget(self.unrecogCheckBox, 10, 3, 1, 1)
        self.branchstateCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.branchstateCheckBox.setObjectName("branchstateCheckBox")
        self.gridLayout_2.addWidget(self.branchstateCheckBox, 10, 7, 1, 1)
        self.nullretCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.nullretCheckBox.setObjectName("nullretCheckBox")
        self.gridLayout_2.addWidget(self.nullretCheckBox, 11, 7, 1, 1)
        self.retvalintCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.retvalintCheckBox.setObjectName("retvalintCheckBox")
        self.gridLayout_2.addWidget(self.retvalintCheckBox, 12, 7, 1, 1)
        self.retvalotherCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.retvalotherCheckBox.setObjectName("retvalotherCheckBox")
        self.gridLayout_2.addWidget(self.retvalotherCheckBox, 13, 7, 1, 1)
        self.varuseCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.varuseCheckBox.setObjectName("varuseCheckBox")
        self.gridLayout_2.addWidget(self.varuseCheckBox, 13, 3, 1, 1)
        self.predboolothersCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.predboolothersCheckBox.setObjectName("predboolothersCheckBox")
        self.gridLayout_2.addWidget(self.predboolothersCheckBox, 12, 6, 1, 1)
        self.namechecksCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.namechecksCheckBox.setObjectName("namechecksCheckBox")
        self.gridLayout_2.addWidget(self.namechecksCheckBox, 5, 7, 1, 1)
        self.isoreservedCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.isoreservedCheckBox.setObjectName("isoreservedCheckBox")
        self.gridLayout_2.addWidget(self.isoreservedCheckBox, 7, 7, 1, 1)
        self.isolibCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.isolibCheckBox.setObjectName("isolibCheckBox")
        self.gridLayout_2.addWidget(self.isolibCheckBox, 14, 0, 1, 1)
        self.exportfcnCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.exportfcnCheckBox.setObjectName("exportfcnCheckBox")
        self.gridLayout_2.addWidget(self.exportfcnCheckBox, 14, 1, 1, 1)
        self.gnuextensionsCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.gnuextensionsCheckBox.setObjectName("gnuextensionsCheckBox")
        self.gridLayout_2.addWidget(self.gnuextensionsCheckBox, 14, 3, 1, 1)
        self.paramuseCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.paramuseCheckBox.setObjectName("paramuseCheckBox")
        self.gridLayout_2.addWidget(self.paramuseCheckBox, 14, 6, 1, 1)
        self.exportheaderCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.exportheaderCheckBox.setObjectName("exportheaderCheckBox")
        self.gridLayout_2.addWidget(self.exportheaderCheckBox, 14, 7, 1, 1)
        self.declundefCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.declundefCheckBox.setObjectName("declundefCheckBox")
        self.gridLayout_2.addWidget(self.declundefCheckBox, 5, 5, 1, 1)
        self.temptransCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.temptransCheckBox.setObjectName("temptransCheckBox")
        self.gridLayout_2.addWidget(self.temptransCheckBox, 7, 5, 1, 1)
        self.trytorecoverCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.trytorecoverCheckBox.setObjectName("trytorecoverCheckBox")
        self.gridLayout_2.addWidget(self.trytorecoverCheckBox, 10, 5, 1, 1)
        self.nullassignCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.nullassignCheckBox.setObjectName("nullassignCheckBox")
        self.gridLayout_2.addWidget(self.nullassignCheckBox, 11, 5, 1, 1)
        self.formatconstCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.formatconstCheckBox.setObjectName("formatconstCheckBox")
        self.gridLayout_2.addWidget(self.formatconstCheckBox, 12, 5, 1, 1)
        self.readonlytransCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.readonlytransCheckBox.setObjectName("readonlytransCheckBox")
        self.gridLayout_2.addWidget(self.readonlytransCheckBox, 13, 5, 1, 1)
        self.noeffectCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.noeffectCheckBox.setObjectName("noeffectCheckBox")
        self.gridLayout_2.addWidget(self.noeffectCheckBox, 14, 5, 1, 1)
        self.globstateCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.globstateCheckBox.setObjectName("globstateCheckBox")
        self.gridLayout_2.addWidget(self.globstateCheckBox, 5, 4, 1, 1)
        self.compdestroyCheckBox = QtGui.QCheckBox(self.SplintOptionsGroupBox)
        self.compdestroyCheckBox.setObjectName("compdestroyCheckBox")
        self.gridLayout_2.addWidget(self.compdestroyCheckBox, 7, 4, 1, 1)
        self.gridLayout_5.addWidget(self.SplintOptionsGroupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 25))
        self.menubar.setObjectName("menubar")
        self.menuSplint_GUI = QtGui.QMenu(self.menubar)
        self.menuSplint_GUI.setObjectName("menuSplint_GUI")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQt = QtGui.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.menuSplint_GUI.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.menubar.addAction(self.menuSplint_GUI.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.ChoosePushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.CheckPushButton.setText(QtGui.QApplication.translate("MainWindow", "Check!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Check mode", None, QtGui.QApplication.UnicodeUTF8))
        self.weakModeRadioButton.setText(QtGui.QApplication.translate("MainWindow", "weak", None, QtGui.QApplication.UnicodeUTF8))
        self.standardModeRadioButton.setText(QtGui.QApplication.translate("MainWindow", "standard", None, QtGui.QApplication.UnicodeUTF8))
        self.checksModeRadioButton.setText(QtGui.QApplication.translate("MainWindow", "checks", None, QtGui.QApplication.UnicodeUTF8))
        self.strictModeRadioButton.setText(QtGui.QApplication.translate("MainWindow", "strict", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Compiler options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Include dirs (e.g. -I<dir1> -I<dir2>:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Defines (e.g. -DDEBUG=1):", None, QtGui.QApplication.UnicodeUTF8))
        self.SplintOptionsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Splint options", None, QtGui.QApplication.UnicodeUTF8))
        self.compdefCheckBox.setText(QtGui.QApplication.translate("MainWindow", "compdef", None, QtGui.QApplication.UnicodeUTF8))
        self.usedefCheckBox.setText(QtGui.QApplication.translate("MainWindow", "usedef", None, QtGui.QApplication.UnicodeUTF8))
        self.matchanyintegralCheckBox.setText(QtGui.QApplication.translate("MainWindow", "matchanyintegral", None, QtGui.QApplication.UnicodeUTF8))
        self.imptypeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "imptype", None, QtGui.QApplication.UnicodeUTF8))
        self.ptrnegateCheckBox.setText(QtGui.QApplication.translate("MainWindow", "ptrnegate", None, QtGui.QApplication.UnicodeUTF8))
        self.bufferoverflowhighCheckBox.setText(QtGui.QApplication.translate("MainWindow", "bufferoverflowhigh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<b>checked means +, unchecked -</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.typeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.mayaliasuniqueCheckBox.setText(QtGui.QApplication.translate("MainWindow", "mayaliasunique", None, QtGui.QApplication.UnicodeUTF8))
        self.boolopsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "boolops", None, QtGui.QApplication.UnicodeUTF8))
        self.nullpassCheckBox.setText(QtGui.QApplication.translate("MainWindow", "nullpass", None, QtGui.QApplication.UnicodeUTF8))
        self.nullderefCheckBox.setText(QtGui.QApplication.translate("MainWindow", "nullderef", None, QtGui.QApplication.UnicodeUTF8))
        self.pathtosplintLabel.setText(QtGui.QApplication.translate("MainWindow", "Path to splint:", None, QtGui.QApplication.UnicodeUTF8))
        self.pathtosplintPushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.formattypeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "formattype", None, QtGui.QApplication.UnicodeUTF8))
        self.onlytransCheckBox.setText(QtGui.QApplication.translate("MainWindow", "onlytrans", None, QtGui.QApplication.UnicodeUTF8))
        self.globsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "globs", None, QtGui.QApplication.UnicodeUTF8))
        self.exportlocalCheckBox.setText(QtGui.QApplication.translate("MainWindow", "exportlocal", None, QtGui.QApplication.UnicodeUTF8))
        self.posixlibCheckBox.setText(QtGui.QApplication.translate("MainWindow", "posixlib", None, QtGui.QApplication.UnicodeUTF8))
        self.unixlibCheckBox.setText(QtGui.QApplication.translate("MainWindow", "unixlib", None, QtGui.QApplication.UnicodeUTF8))
        self.warnposixCheckBox.setText(QtGui.QApplication.translate("MainWindow", "warnposix", None, QtGui.QApplication.UnicodeUTF8))
        self.posixstrictlibCheckBox.setText(QtGui.QApplication.translate("MainWindow", "posixstrictlib", None, QtGui.QApplication.UnicodeUTF8))
        self.preprocCheckBox.setText(QtGui.QApplication.translate("MainWindow", "preproc", None, QtGui.QApplication.UnicodeUTF8))
        self.mustfreefreshCheckBox.setText(QtGui.QApplication.translate("MainWindow", "mustfreefresh", None, QtGui.QApplication.UnicodeUTF8))
        self.unrecogCheckBox.setText(QtGui.QApplication.translate("MainWindow", "unrecog", None, QtGui.QApplication.UnicodeUTF8))
        self.branchstateCheckBox.setText(QtGui.QApplication.translate("MainWindow", "branchstate", None, QtGui.QApplication.UnicodeUTF8))
        self.nullretCheckBox.setText(QtGui.QApplication.translate("MainWindow", "nullret", None, QtGui.QApplication.UnicodeUTF8))
        self.retvalintCheckBox.setText(QtGui.QApplication.translate("MainWindow", "retvalint", None, QtGui.QApplication.UnicodeUTF8))
        self.retvalotherCheckBox.setText(QtGui.QApplication.translate("MainWindow", "retvalother", None, QtGui.QApplication.UnicodeUTF8))
        self.varuseCheckBox.setText(QtGui.QApplication.translate("MainWindow", "varuse", None, QtGui.QApplication.UnicodeUTF8))
        self.predboolothersCheckBox.setText(QtGui.QApplication.translate("MainWindow", "predboolothers", None, QtGui.QApplication.UnicodeUTF8))
        self.namechecksCheckBox.setText(QtGui.QApplication.translate("MainWindow", "namechecks", None, QtGui.QApplication.UnicodeUTF8))
        self.isoreservedCheckBox.setText(QtGui.QApplication.translate("MainWindow", "isoreserved", None, QtGui.QApplication.UnicodeUTF8))
        self.isolibCheckBox.setText(QtGui.QApplication.translate("MainWindow", "isolib", None, QtGui.QApplication.UnicodeUTF8))
        self.exportfcnCheckBox.setText(QtGui.QApplication.translate("MainWindow", "exportfcn", None, QtGui.QApplication.UnicodeUTF8))
        self.gnuextensionsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "gnuextensions", None, QtGui.QApplication.UnicodeUTF8))
        self.paramuseCheckBox.setText(QtGui.QApplication.translate("MainWindow", "paramuse", None, QtGui.QApplication.UnicodeUTF8))
        self.exportheaderCheckBox.setText(QtGui.QApplication.translate("MainWindow", "exportheader", None, QtGui.QApplication.UnicodeUTF8))
        self.declundefCheckBox.setText(QtGui.QApplication.translate("MainWindow", "declundef", None, QtGui.QApplication.UnicodeUTF8))
        self.temptransCheckBox.setText(QtGui.QApplication.translate("MainWindow", "temptrans", None, QtGui.QApplication.UnicodeUTF8))
        self.trytorecoverCheckBox.setText(QtGui.QApplication.translate("MainWindow", "trytorecover", None, QtGui.QApplication.UnicodeUTF8))
        self.nullassignCheckBox.setText(QtGui.QApplication.translate("MainWindow", "nullassign", None, QtGui.QApplication.UnicodeUTF8))
        self.formatconstCheckBox.setText(QtGui.QApplication.translate("MainWindow", "formatconst", None, QtGui.QApplication.UnicodeUTF8))
        self.readonlytransCheckBox.setText(QtGui.QApplication.translate("MainWindow", "readonlytrans", None, QtGui.QApplication.UnicodeUTF8))
        self.noeffectCheckBox.setText(QtGui.QApplication.translate("MainWindow", "noeffect", None, QtGui.QApplication.UnicodeUTF8))
        self.globstateCheckBox.setText(QtGui.QApplication.translate("MainWindow", "globstate", None, QtGui.QApplication.UnicodeUTF8))
        self.compdestroyCheckBox.setText(QtGui.QApplication.translate("MainWindow", "compdestroy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSplint_GUI.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About SplintGUI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("MainWindow", "AboutQt", None, QtGui.QApplication.UnicodeUTF8))

